### ISSUE TITLE
Search Details Page / DOI Landing Page

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#20]
Design and Implement

**Comment by mdrum** [comment]
I've completed the initial implementation of the DOI landing pages. You can [see those changes here](https://sbnarchivedemo.psi.edu/?identifier=urn:nasa:pds:cassini_iss_saturn:browse_raw&mockup=true)

This code is pushed to [doi-mockup branch](https://github.com/NASA-PDS/archive-viewer/tree/feature/doi-mockup)

Some known differences from mockups, with room for discussion:
- I kept some of the iconography that we had initially in our design
- The pill appended to the title is "PDS4 Bundle/Collection" instead of just "Bundle/Collection" because it also needed to support PDS3
- I left Observing System components on the sidebar, as we originally had it on our site (still labeled as Spacecraft/Mission/Instrument) since I believe that's a better place for it, but it was also just easier.
- I only auto-collapsed those side boxes if there are more than three items
- I did not auto-expand the details on the high width breakpoint mostly because I really just ran out of time to do anything fancy ensuring that the primary Browse button was always visible above the fold
- The Citation Builder is just some arbitrary patterns that show how we could go about dynamically constructing citations for the user. I looked into adding some real examples, but quickly realized how complicated and varied (and undocumented) widely-used citation styles are

Some additional handy new features to be aware of on that deployment:
- If you append `&mockup=true` to the URL, additional mockup data will be integrated into the dataset pages, to highlight the additional features
- If you append `&pdsOnly=true` to the URL, then any additional metadata that we have supplemented as part of the Archive Loader at PSI will be left out of the pages (so you can see results purely from the PDS core registry).

Meta-note: I'm out next week so don't find anything too broken too soon

**Comment by jordanpadams** [comment]
October Schedule Status ⏳:  On track

**Comment by Astro-Joni** [comment]
1

**Comment by edwardbarraza** [comment]
Here is some crit for what is [here](https://sbnarchivedemo.psi.edu/?identifier=urn:nasa:pds:cassini_iss_saturn:browse_raw&mockup=true)
- Is this supposed to adhere to our dark theme that we defined?
- I think removing 'relevant tags' is ok. They are removed when adjusted for mobile, so I think it ok to remove this all together
- Regarding the right-hand container (other versions, PDS3 Versions, etc.), is this something we can potentially push back in to an accordion header, much like 'show more'? Why do we have this in its own container (what makes it so special?)
- Also, no good reason to have each version to be contained in their own card. We can just contain them in to one accordion or module container as you see in the mockup I've attached
- I am confused as to why we use 'bundle' and 'dataset' when concerning Bundles. Are they the same thing? Or are we nudging user to browse the _collection_ with the button? I am not sure what the distinction is.
- We don't have that sized button defined in the design system - it is a bit excessive
- Here is a mockup of what it should look like in the theme

<img width="1280" alt="DOI Landing Page (L Breakpoint)" src="https://user-images.githubusercontent.com/26258411/98038534-240b7380-1dd2-11eb-8cca-c15fc146e87a.png">

**Comment by jordanpadams** [comment]
> Is this supposed to adhere to our dark theme that we defined?

Per Mike, we will create new ticket to track converting to using dark theme.

> I think removing 'relevant tags' is ok. They are removed when adjusted for mobile, so I think it ok to remove this all together

Will be removed.

> Regarding the right-hand container (other versions, PDS3 Versions, etc.), is this something we can potentially push back in to an accordion header, much like 'show more'? Why do we have this in its own container (what makes it so special?) Also, no good reason to have each version to be contained in their own card. We can just contain them in to one accordion or module container as you see in the mockup I've attached

Mike will try out accordion as an alternative to see if it makes sense to use instead of cards.

> I am confused as to why we use 'bundle' and 'dataset' when concerning Bundles. Are they the same thing? Or are we nudging user to browse the collection with the button? I am not sure what the distinction is.

Mike to try out some different layouts to make this distinction more clear.

> We don't have that sized button defined in the design system - it is a bit excessive

Will look to figure out a better way to display this.

> We have icons defined in the design system - I have swapped for our flat 'folder' icon.

Copy. Mike will look into this.

**Comment by jordanpadams** [comment]
@edwardbarraza can you provide a link to the figma mockup you have above?

**Comment by edwardbarraza** [comment]
Here is the link for the [DOI work in Figma](https://www.figma.com/file/D7n5ODxbsHu3DDxE3ykIUV/DOI?node-id=687%3A0)

I can also link to the Design System that is still WIP, [here](https://www.figma.com/file/HN4cQ7tyBw5SaPc8GesLpr/Design-System?node-id=3073%3A0)

**Comment by jordanpadams** [comment]
Closing out this Epic per comments above and sub-ticket completion. See https://sbnarchivedemo.psi.edu/?identifier=urn:nasa:pds:cassini_iss_saturn:data_raw&mockup=true
