### ISSUE TITLE
Complete revisions for Context Browser landing Pages per UX feedback

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS.nasa.gov-Search#27]
See comments in #2 for revisions

**Comment by jordanpadams** [comment]
@edwardbarraza to supply a revision to his Figma output and provide a checklist of items for updates

**Comment by edwardbarraza** [comment]
![Alternate (L Breakpoint)-1](https://user-images.githubusercontent.com/26258411/98349121-774a1580-1fce-11eb-8904-610242eb30a6.png)
![Alternate (L Breakpoint)](https://user-images.githubusercontent.com/26258411/98349127-7913d900-1fce-11eb-84df-ed110528bcb5.png)

- [ ] Move right-hand cards for versions and legacy and insert them in to an accordion folder as seen in image above. 
- [ ] Convert to dark theme (check [Figma](https://www.figma.com/file/D7n5ODxbsHu3DDxE3ykIUV/DOI?node-id=687%3A0) to get exact hex values for colors) 
- [ ] Re-size 'BROWSE BUNDLE' button 238 X 34.4 (follow visual language conventions)
- [ ] Replace folder icon with the one that is defined within the design system (SVG attached in next comment)
- [ ] Move citation in to an accordion

If clarification is required, please do not hesitate to ask!

**Comment by mdrum** [comment]
I see what you all meant about Accordions now. I had skipped over that component because it's [no longer a part of the Material Design guidelines](https://material-ui.com/components/accordion/). It looks like they're still supported by the React component library though, so I can use them.

As for the Browse Bundle button: I think there's some confusion around the difference between a Bundle and Collection; the mockups you have there are for a Collection, and it needs two buttons: one to "Browse the Collection", and another less prominent button to navigate to the Bundle that contains that Collection. I can improvise on that, but if you'd like to update the mockups to match that functionality I can implement it that way @edwardbarraza.

**Comment by mdrum** [comment]
Here are some screenshots of my progress. Note how I handled the Browse Collection / View Bundle buttons.
 
(Cross-posted from #28)
![CleanShot 2020-11-12 at 16 57 58@2x](https://user-images.githubusercontent.com/31220657/99011095-8b2ed380-2508-11eb-925b-bbb89369bbd6.png)
![CleanShot 2020-11-12 at 17 02 51@2x](https://user-images.githubusercontent.com/31220657/99011272-fa0c2c80-2508-11eb-831b-de77fb131a38.png)

I plan to deploy these changes tomorrow, and we can go over them in the meeting.

**Comment by tloubrieu-jpl** [comment]
@mdrum this looks good and Edward is going to use your demo page for the Managent Council presentation today.
